---
- name: Configuration du serveur LDAP
  hosts: ldap
  become: yes
  roles:
    - ldap
  tags: ldap

- name: Installation de Nextcloud
  hosts: nextcloud
  become: yes
  roles:
    - nextcloud
  tags: nextcloud

- name: Installation de Odoo ERP
  hosts: odoo
  become: yes
  roles:
    - odoo
  tags: odoo

- name: Installation de l'API Badges
  hosts: badge-backend
  become: yes
  roles:
    - badge-backend
  tags: badge

- name: Installation du serveur de backup
  hosts: backup
  become: yes
  roles:
    - backup
  tags: backup

- name: Installation du serveur SIEM Wazuh
  hosts: siem
  become: yes
  roles:
    - wazuh
  tags: siem

- name: Installation du serveur VPN WireGuard
  hosts: vpn
  become: yes
  roles:
    - wireguard
  tags: vpn

- name: Installation du serveur Mail (Mailcow)
  hosts: mail
  become: yes
  roles:
    - mailcow
  tags: mail

- name: Installation de OnlyOffice Community Server
  hosts: office
  become: yes
  roles:
    - onlyoffice
  tags: office

- name: Installation du Wiki BookStack
  hosts: wiki
  become: yes
  roles:
    - bookstack
  tags: wiki

- name: Installation de Nginx Proxy Manager
  hosts: npm
  become: yes
  roles:
    - nginx-proxy-manager

- name: Installation de Jitsi Meet
  hosts: jitsi
  become: yes
  roles:
    - jitsi

- name: Installation de Jitsi Meet
  hosts: jitsi
  become: yes
  roles:
    - jitsi

- name: Installation de Vaultwarden
  hosts: vaultwarden
  become: yes
  roles:
    - vaultwarden
