---
- name: Configuration du serveur LDAP
  hosts: ldap
  become: yes
  roles:
    - ldap
  tags: ldap

- name: Installation de Nextcloud
  hosts: nextcloud
  become: yes
  roles:
    - nextcloud
  tags: nextcloud
